SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `dinfindb` DEFAULT CHARACTER SET utf8 ;
USE `dinfindb` ;

-- -----------------------------------------------------
-- Table `dinfindb`.`CUSTINFO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`CUSTINFO` (
  `CI_CUSTID` VARCHAR(17) NOT NULL COMMENT 'Store Customer ID. Total 14 characters.\\n2 - CountryCode\\n3 - City\\n2 - BranchID\\n4 - Last to digit of Year and two digit of month\\n4 - Sequence Number\\nE.g, INCHN0113010001\\n' ,
  `CI_FNAME` VARCHAR(45) NOT NULL ,
  `CI_MNAME` VARCHAR(10) NULL ,
  `CI_LNAME` VARCHAR(45) NOT NULL ,
  `CI_GENDER` CHAR NOT NULL ,
  `CI_BDATE` DATE NULL ,
  `CI_STATUS` CHAR(1) NOT NULL DEFAULT 'Y' ,
  `CI_CRTEMPID` INT(10) NULL ,
  `CI_DATEINS` DATETIME NULL ,
  `CI_DATEUPD` DATETIME NULL ,
  `CI_COAPPID` VARCHAR(17) NULL ,
  `CI_COAPPREL` VARCHAR(15) NULL ,
  PRIMARY KEY (`CI_CUSTID`) ,
  UNIQUE INDEX `CI_ID_UNIQUE` (`CI_CUSTID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`CUSTREFERRALS`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`CUSTREFERRALS` (
  `CR_CUSTID` VARCHAR(17) NOT NULL ,
  `CR_REFERALIDS` VARCHAR(2500) NULL COMMENT 'Store the referral customer ids' ,
  `CR_DATEINS` DATETIME NULL ,
  `CR_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `CR_REFNAME` VARCHAR(45) NULL ,
  `CR_EMPID` INT(10) NULL ,
  `CR_DATAUPD` DATETIME NULL ,
  PRIMARY KEY (`CR_CUSTID`) ,
  CONSTRAINT `CUSTID`
    FOREIGN KEY (`CR_CUSTID` )
    REFERENCES `dinfindb`.`CUSTINFO` (`CI_CUSTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPINFO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPINFO` (
  `EI_EMPID` INT(10) NOT NULL AUTO_INCREMENT COMMENT 'Store Customer ID. Total 5 characters.\\nE.g, 10001\\n' ,
  `EI_TITLE` CHAR(5) NULL ,
  `EI_FNAME` VARCHAR(45) NOT NULL ,
  `EI_MNAME` VARCHAR(10) NULL ,
  `EI_LNAME` VARCHAR(45) NOT NULL ,
  `EI_BDATE` DATE NULL ,
  `EI_GENDER` CHAR NULL ,
  `EI_STATUS` CHAR(1) NOT NULL DEFAULT 'Y' ,
  `EI_JOINDATE` DATE NULL ,
  `EI_ENDDATE` DATE NULL ,
  `EI_VERISTATUS` CHAR NULL DEFAULT 'N' ,
  `EI_ROLE` VARCHAR(5) NULL ,
  `EI_BRANCHCODE` VARCHAR(5) NULL ,
  `EI_EMAIL` VARCHAR(45) NULL ,
  `EI_LPHONE` BIGINT(15) UNSIGNED NULL ,
  `EI_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `EI_LOGINCRT` CHAR NULL DEFAULT 'N' ,
  `EI_NOOFDEP` INT(2) NULL ,
  `EI_RELIGION` VARCHAR(10) NULL ,
  `EI_CASTE` VARCHAR(5) NULL ,
  `EI_DATEINS` DATETIME NULL ,
  `EI_DATEUPD` DATETIME NULL ,
  `EI_ADDEDBY` INT(10) NULL ,
  `EI_UPDATEDBY` INT(10) NULL ,
  PRIMARY KEY (`EI_EMPID`) ,
  UNIQUE INDEX `CI_ID_UNIQUE` (`EI_EMPID` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`CUSTADDR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`CUSTADDR` (
  `CA_ADDRID` BIGINT NOT NULL ,
  `CA_CUSTID` VARCHAR(17) NULL ,
  `CA_ADDRTYPE` VARCHAR(8) NOT NULL ,
  `CA_ADDRESS1` VARCHAR(50) NULL ,
  `CA_ADDRESS2` VARCHAR(50) NULL ,
  `CA_ADDRESS3` VARCHAR(50) NULL ,
  `CA_AREA` VARCHAR(50) NULL ,
  `CA_CITYCODE` VARCHAR(50) NULL ,
  `CA_STATECODE` VARCHAR(5) NULL ,
  `CA_PINCODE` INT(6) NULL ,
  `CA_CNTRYCODE` VARCHAR(5) NULL COMMENT 'Store Customer Address history based on the address type like Home and Work' ,
  `CA_STATUS` CHAR NULL ,
  `CA_FRMDATE` DATE NULL ,
  `CA_TODATE` DATE NULL ,
  `CA_CRTEMPID` INT(10) NULL ,
  `CA_UPTEMPID` INT(10) NULL ,
  `CA_CRTTIME` DATETIME NULL ,
  `CA_UPDTIME` DATETIME NULL ,
  INDEX `CUSTID_idx` (`CA_CUSTID` ASC) ,
  PRIMARY KEY (`CA_ADDRID`) ,
  CONSTRAINT `CI_CA_CUSTID`
    FOREIGN KEY (`CA_CUSTID` )
    REFERENCES `dinfindb`.`CUSTINFO` (`CI_CUSTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`LOGININFO`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`LOGININFO` (
  `LI_USERID` INT(10) NOT NULL ,
  `LI_PASSWORD` VARCHAR(32) NOT NULL ,
  `LI_STATUS` CHAR(1) NOT NULL DEFAULT 'Y' ,
  `LI_LOGINSTATUS` CHAR(1) NOT NULL DEFAULT 'N' ,
  `LI_LASTLOGIN` DATETIME NULL ,
  `LI_DATEINS` DATETIME NULL ,
  `LI_DATEUPD` DATETIME NULL ,
  `LI_ADDEDBY` INT(10) NULL ,
  `LI_UPDATEDBY` INT(10) NULL ,
  INDEX `EMPLID_idx` (`LI_USERID` ASC) ,
  PRIMARY KEY (`LI_USERID`) ,
  CONSTRAINT `EI_LI_EMPID`
    FOREIGN KEY (`LI_USERID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPADDR`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPADDR` (
  `EA_ADDRID` BIGINT NOT NULL AUTO_INCREMENT ,
  `EA_EMPID` INT(10) NULL ,
  `EA_ADDRTYPE` VARCHAR(8) NULL ,
  `EA_ADDRESS1` VARCHAR(50) NULL ,
  `EA_ADDRESS2` VARCHAR(50) NULL ,
  `EA_ADDRESS3` VARCHAR(50) NULL ,
  `EA_AREA` VARCHAR(50) NOT NULL ,
  `EA_CITYCODE` VARCHAR(5) NULL ,
  `EA_STATECODE` VARCHAR(5) NULL ,
  `EA_CNTRYCODE` VARCHAR(5) NULL ,
  `EA_STATUS` CHAR(1) NOT NULL ,
  `EA_FRMDATE` DATE NULL ,
  `EA_TODATE` DATE NULL ,
  `EA_DATEINS` DATETIME NULL ,
  `EA_DATEUPD` DATETIME NULL ,
  `EA_ADDEDBY` INT(10) NULL ,
  `EA_UPDATEDBY` INT(10) NULL ,
  INDEX `EMPID_idx` (`EA_EMPID` ASC) ,
  PRIMARY KEY (`EA_ADDRID`) ,
  CONSTRAINT `EI_EA_EMPID`
    FOREIGN KEY (`EA_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPCOMM`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPCOMM` (
  `EC_COMMID` BIGINT NOT NULL AUTO_INCREMENT ,
  `EC_EMPID` INT(10) NULL ,
  `EC_HPHONE` BIGINT(15) UNSIGNED NULL ,
  `EC_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `EC_PEMAIL` VARCHAR(75) NULL ,
  `EC_WEMAIL` VARCHAR(75) NULL ,
  `EC_DATEINS` DATETIME NULL ,
  `EC_DATEUPD` DATETIME NULL ,
  `EC_ADDEDBY` INT(10) NULL ,
  `EC_UPDATEBY` INT(10) NULL ,
  PRIMARY KEY (`EC_COMMID`) ,
  INDEX `EC_EMPID_idx` (`EC_EMPID` ASC) ,
  CONSTRAINT `EI_EC_EMPID`
    FOREIGN KEY (`EC_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`CUSTCOMM`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`CUSTCOMM` (
  `CC_COMMID` BIGINT NOT NULL ,
  `CC_CUSTID` VARCHAR(17) NULL ,
  `CC_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `CC_HPHONE` BIGINT(15) UNSIGNED NULL ,
  `CC_WPHONE` BIGINT(15) UNSIGNED NULL ,
  `CC_PEMAIL` VARCHAR(75) NULL ,
  `CC_WEMAIL` VARCHAR(75) NULL ,
  `CC_INCOME` FLOAT NULL ,
  `CC_INCSLAB` INT(5) NULL ,
  `CC_STATUS` CHAR NOT NULL ,
  `CC_CRTEMPID` INT(10) NULL ,
  `CC_UPDEMPID` INT(10) NULL ,
  `CC_CRTTIME` DATETIME NULL ,
  `CC_UPDTIME` DATETIME NULL ,
  PRIMARY KEY (`CC_COMMID`) ,
  INDEX `CUSTCOMM_idx` (`CC_CUSTID` ASC) ,
  CONSTRAINT `CI_CC_CUSTID`
    FOREIGN KEY (`CC_CUSTID` )
    REFERENCES `dinfindb`.`CUSTINFO` (`CI_CUSTID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`MENUCATEG`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`MENUCATEG` (
  `MC_MENUCATEID` INT(2) NOT NULL ,
  `MC_MENUNAME` VARCHAR(45) NULL ,
  `MC_CRTTIME` DATETIME NULL ,
  PRIMARY KEY (`MC_MENUCATEID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`MENUSUBCATEG`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`MENUSUBCATEG` (
  `MS_MENUSUBID` INT(2) NOT NULL ,
  `MS_MAINMENUID` INT(2) NULL ,
  `MS_MAINSUBNAME` VARCHAR(45) NULL ,
  `MS_CRTTIME` DATETIME NULL ,
  PRIMARY KEY (`MS_MENUSUBID`) ,
  CONSTRAINT `MENUFID`
    FOREIGN KEY (`MS_MENUSUBID` )
    REFERENCES `dinfindb`.`MENUCATEG` (`MC_MENUCATEID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPPREVEXP`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPPREVEXP` (
  `EP_PREVEXPID` BIGINT NOT NULL AUTO_INCREMENT ,
  `EP_EMPID` INT(10) NULL ,
  `EP_COMPNAME` VARCHAR(45) NULL ,
  `EP_SALARY` FLOAT(15) NULL ,
  `EP_ROLE` VARCHAR(45) NULL ,
  `EP_SKILLS` VARCHAR(100) NULL ,
  `EP_NOOFYRS` TINYINT(4) NULL ,
  `EP_JOINDATE` DATETIME NULL ,
  `EP_ENDDATE` DATETIME NULL ,
  `EP_ADDRESS1` VARCHAR(50) NULL ,
  `EP_ADDRESS2` VARCHAR(50) NULL ,
  `EP_ADDRESS3` VARCHAR(50) NULL ,
  `EP_AREA` VARCHAR(50) NULL ,
  `EP_CITYCODE` VARCHAR(5) NULL ,
  `EP_STATECODE` VARCHAR(5) NULL ,
  `EP_CONTRYCODE` VARCHAR(5) NULL ,
  `EP_DATEINS` DATETIME NULL ,
  `EP_DATEUPD` DATETIME NULL ,
  `EP_ADDEDBY` INT(10) NULL ,
  `EP_UPDATEBY` INT(10) NULL ,
  INDEX `EMPID_idx` (`EP_EMPID` ASC) ,
  PRIMARY KEY (`EP_PREVEXPID`) ,
  CONSTRAINT `EI_EP_EMPID`
    FOREIGN KEY (`EP_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPIDEN`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPIDEN` (
  `ED_IDENID` BIGINT NOT NULL AUTO_INCREMENT ,
  `ED_EMPID` INT NULL ,
  `ED_IDTYPE` VARCHAR(5) NULL ,
  `ED_IDNO` VARCHAR(45) NULL ,
  `ED_DOCLOC` VARCHAR(250) NULL ,
  `ED_DATEINS` DATETIME NULL ,
  `ED_DATEUPD` DATETIME NULL ,
  `ED_ADDEDBY` INT(10) NULL ,
  `ED_UPDATEBY` INT(10) NULL ,
  INDEX `EI_ED_EMPID_idx` (`ED_EMPID` ASC) ,
  PRIMARY KEY (`ED_IDENID`) ,
  CONSTRAINT `EI_ED_EMPID`
    FOREIGN KEY (`ED_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPEDU`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPEDU` (
  `EE_EDUID` BIGINT NOT NULL AUTO_INCREMENT ,
  `EE_EMPID` INT(10) NULL ,
  `EE_TYPECODE` VARCHAR(5) NULL ,
  `EE_QUAL` VARCHAR(45) NULL ,
  `EE_DEGREECODE` VARCHAR(5) NULL ,
  `EE_SPEICALIST` VARCHAR(45) NULL ,
  `EE_INSTITUTATION` VARCHAR(75) NULL ,
  `EE_ADDRESS` VARCHAR(50) NULL ,
  `EE_CITYCODE` VARCHAR(5) NULL ,
  `EE_STATECODE` VARCHAR(5) NULL ,
  `EE_CONTRYCODE` VARCHAR(5) NULL ,
  `EE_DATEINST` DATETIME NULL ,
  `EE_DATEUPD` DATETIME NULL ,
  `EE_ADDEDBY` INT(10) NULL ,
  `EE_UPDATEDBY` INT(10) NULL ,
  `EMPEDUcol` VARCHAR(45) NULL ,
  `EMPEDUcol1` VARCHAR(45) NULL ,
  INDEX `EMPID_idx` (`EE_EMPID` ASC) ,
  PRIMARY KEY (`EE_EDUID`) ,
  CONSTRAINT `EI_EE_EMPID`
    FOREIGN KEY (`EE_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPBANKDET`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPBANKDET` (
  `EB_BANKDETID` BIGINT NOT NULL AUTO_INCREMENT ,
  `EB_EMPID` INT(10) NULL ,
  `EB_NAMECODE` VARCHAR(5) NULL ,
  `EB_BRANCHCODE` VARCHAR(5) NULL ,
  `EB_ACTYPE` VARCHAR(5) NULL ,
  `EB_ACCTNO` BIGINT NULL ,
  `EB_STATECODE` VARCHAR(5) NULL ,
  `EB_CITYCODE` VARCHAR(5) NULL ,
  `EB_CONTYCODE` VARCHAR(5) NULL ,
  `EB_STATUS` CHAR NULL ,
  `EB_STARTDTE` DATETIME NULL ,
  `EB_ENDDTE` DATETIME NULL ,
  `EB_DATEINS` DATETIME NULL ,
  `EB_DATEUPD` DATETIME NULL ,
  `EB_ADDEDBY` INT(10) NULL ,
  `EB_UPDATEDBY` INT(10) NULL ,
  PRIMARY KEY (`EB_BANKDETID`) ,
  INDEX `EI_EB_EMPID_idx` (`EB_EMPID` ASC) ,
  CONSTRAINT `EI_EB_EMPID`
    FOREIGN KEY (`EB_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPEMRCONT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPEMRCONT` (
  `ER_EMPID` INT(10) NOT NULL ,
  `ER_RELATIONSHIP` VARCHAR(15) NULL ,
  `ER_TITLE` CHAR(5) NULL ,
  `ER_FNAME` VARCHAR(45) NULL ,
  `ER_MNAME` VARCHAR(10) NULL ,
  `ER_LNAME` VARCHAR(45) NULL ,
  `ER_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `ER_APHONE` BIGINT(15) UNSIGNED NULL ,
  `ER_DATEINS` DATETIME NULL ,
  `ER_DATEUPD` DATETIME NULL ,
  `ER_ADDEDBY` INT(10) NULL ,
  `ER_UPDATEDBY` INT(10) NULL ,
  PRIMARY KEY (`ER_EMPID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPDEPDENT`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPDEPDENT` (
  `EDD_EMPID` INT(10) NULL ,
  `EDD_RELSHIP` VARCHAR(15) NULL ,
  `EDD_TITLE` CHAR(5) NULL ,
  `EDD_FNAME` VARCHAR(45) NULL ,
  `EDD_MNAME` VARCHAR(10) NULL ,
  `EDD_LNAME` VARCHAR(45) NULL ,
  `EDD_BDATE` DATETIME NULL ,
  `EDD_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `EDD_LPHONE` BIGINT(15) UNSIGNED NULL ,
  `EDD_EMRCONT` CHAR NULL DEFAULT 'Y' ,
  `EDD_ADDEDBY` INT(10) NULL ,
  `EDD_UPDATEDBY` INT(10) NULL ,
  `EDD_DATEINS` DATETIME NULL ,
  `EDD_DATEUPD` DATETIME NULL ,
  INDEX `EI_EDD_EMPID_idx` (`EDD_EMPID` ASC) ,
  CONSTRAINT `EI_EDD_EMPID`
    FOREIGN KEY (`EDD_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPPEXPREF`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPPEXPREF` (
  `EPR_EMPID` INT(10) NULL ,
  `EPR_RELSHIP` VARCHAR(15) NULL ,
  `EPR_ROLE` VARCHAR(15) NULL ,
  `EPR_TITLE` CHAR(5) NULL ,
  `EPR_FNAME` VARCHAR(45) NULL ,
  `EPR_MNAME` VARCHAR(10) NULL ,
  `EPR_LNAME` VARCHAR(45) NULL ,
  `EPR_MPHONE` BIGINT(15) UNSIGNED NULL ,
  `EPR_LPHONE` BIGINT(15) UNSIGNED NULL ,
  `EPR_ADDEDBY` INT(10) NULL ,
  `EPR_UPDATEDBY` INT(10) NULL ,
  `EPR_DATEINS` DATETIME NULL ,
  `EPR_DATEUPD` DATETIME NULL ,
  INDEX `EI_EPR_EMPID_idx` (`EPR_EMPID` ASC) ,
  CONSTRAINT `EI_EPR_EMPID`
    FOREIGN KEY (`EPR_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dinfindb`.`EMPROLE`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `dinfindb`.`EMPROLE` (
  `ER_EMPID` INT(10) NULL ,
  `ER_ROLEID` VARCHAR(5) NULL ,
  `ER_BRANCHCODE` VARCHAR(10) NULL ,
  `ER_STATUS` CHAR NULL ,
  `ER_STRDATE` DATETIME NULL ,
  `ER_ENDDATE` DATETIME NULL ,
  `ER_DATEINS` DATETIME NULL ,
  `ER_DATEUPD` DATETIME NULL ,
  `ER_ADDEDBY` INT(10) NULL ,
  `ER_UPDATEDBY` INT(10) NULL ,
  INDEX `EI_ER_EMPID_idx` (`ER_EMPID` ASC) ,
  CONSTRAINT `EI_ER_EMPID`
    FOREIGN KEY (`ER_EMPID` )
    REFERENCES `dinfindb`.`EMPINFO` (`EI_EMPID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


CREATE USER `Dinesh` IDENTIFIED BY 'dinesh#1234';

grant ALL on SCHEMA **.* to Dinesh;
CREATE USER `Saravanan` IDENTIFIED BY 'sara#1234';

grant EXECUTE on ROUTINE **.* to Saravanan;
grant ALL on SCHEMA **.* to Saravanan;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
